### ISSUE TITLE
possible numerical error in hupdate

### ISSUE THREAD

**Issue by jianxiaoyang** [Merck/gsdmvn#26]
The output `h` of old `hupdate_()` (in R) and new `hupdate()` (in Rcpp) do not quite match, the maximum absolute error is ~`e-17`:

```
library(gsdmvn)

# old function in R
g1 = gsdmvn:::hupdate_()

# new function in Rcpp
g2 = hupdate()

# maximum absolute error
max(abs(g1$h - g2$h)) # 2.081668e-17
```

**Comment by nanxstats** [comment]
I think we are good here. The maximum absolute error is still smaller than the smallest positive floating point number. [`all.equal()`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/all.equal.html) uses an even more relaxed default tolerance `sqrt(.Machine$double.eps)` which is around 1.5e-8.

```r
g1 = gsdmvn:::hupdate_()
g2 = gsdmvn::hupdate()

max(abs(g1$h - g2$h))
#> [1] 2.081668e-17

.Machine$double.eps
#> [1] 2.220446e-16

max(abs(g1$h - g2$h)) < .Machine$double.eps
#> [1] TRUE

all.equal(g1$h, g2$h)
#> [1] TRUE

identical(g1$h, g2$h)
#> [1] FALSE
```
