### ISSUE TITLE
Add milestone test in fixed_design

### ISSUE THREAD

**Issue by keaven** [Merck/gsdmvn#33]
This can presumably be modeled after fixed_design_rmst(). 
We need to add an argument, say 'milestone' that defines the timing of the milestone.
It should be > 0 and less than (or equal to???) studyDuration.
For the x value, I would probably call it "Milestone".
If we are trying to keep names short, can we be forgiving and translate 'x' to lower case so people could use "Milestone" or "milestone". 
We could also have things like "MaxCombo" or "MC" being acceptable for input to x...meaning we could add the shorter "ms" here for milestone; this may simplify things for the user without adding many problems for the code. 
The key code from npsurvSS is: 
size_two_arm(arm0, arm1, list(test="survival difference", milestone=12))
which can be swapped in line 32 of fixed_design_rmst.r.

**Comment by LittleBeannie** [comment]
See updates in PR: https://github.com/Merck/gsdmvn/pull/34
