### ISSUE TITLE
binary outcome

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/gsdmvn#9]
work on gs_info_rd() (or a different name) for binary outcome

**Comment by keaven** [comment]
rd = risk difference. There are some different challenges here and this provides an example. We will also produce gs_power_rd and gs_design_rd. Alternate name could be gs_xxx_binomial, but this option allows something like gs_info_rr() for risk ratio and gs_info_or for odds-ratio. Keeping these separate makes coding simpler for each one and makes treatment effect scale more transparent. Fleiss-Tytun-Ury reference justifies risk difference as a good choice.
